In [1]:
import os, sys

In [2]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
os.chdir('/content/drive/MyDrive')

sys.path.append("/content/drive/My Drive/")

In [5]:
import numpy as np

In [6]:
import matplotlib.pyplot as plt
import pandas as pd

# **Importing the dataset**

In [7]:
dataset = pd.read_csv('cardata.csv')

In [8]:
dataset

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [9]:
X = dataset[['Present_Price','Kms_Driven','Fuel_Type','Transmission']]
y = dataset['Selling_Price']

In [10]:
X

     Present_Price  Kms_Driven Fuel_Type Transmission
0             5.59       27000    Petrol       Manual
1             9.54       43000    Diesel       Manual
2             9.85        6900    Petrol       Manual
3             4.15        5200    Petrol       Manual
4             6.87       42450    Diesel       Manual
..             ...         ...       ...          ...
296          11.60       33988    Diesel       Manual
297           5.90       60000    Petrol       Manual
298          11.00       87934    Petrol       Manual
299          12.50        9000    Diesel       Manual
300           5.90        5464    Petrol       Manual

[301 rows x 4 columns]

In [11]:
y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

# **Encoding Categorical variable**

In [12]:
X = dataset.iloc[:, [0, 5]]

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [0, 1])
    ],
    remainder='passthrough'
)

X = ct.fit_transform(X)

In [14]:
X

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# **Splitting the dataset into the Training set and Test**

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/2)

# **Training the Multiple Linear Regression model on the Training set**

In [16]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [17]:
y_pred = regressor.predict(X_test)

In [18]:
y_pred

array([ 2.57895163,  8.15631399,  6.26907584,  6.56043128,  6.26907584,
        5.075     ,  7.62551466,  0.31      ,  2.57895163,  8.15631399,
        1.09      ,  2.57895163,  4.67319312,  1.65      ,  0.5       ,
        0.6       ,  2.7875    ,  2.57895163,  9.15058848,  6.26907584,
        7.62551466,  2.62857143,  0.55      ,  2.57895163,  2.57895163,
        1.09      ,  6.4       ,  2.57895163,  4.61082346,  2.57895163,
        4.65      ,  7.62551466,  2.57895163,  2.57895163,  4.17483435,
        2.57895163,  2.57895163,  0.72      ,  0.65      , 18.37714286,
        7.59588271,  2.62857143,  1.75      ,  0.625     ,  2.57895163,
        3.90411729,  4.5       ,  7.62551466,  4.1       ,  0.78      ,
        6.56043128,  6.55235273,  2.57895163,  2.57895163,  2.57895163,
        6.56043128, 18.37714286,  2.57895163,  2.57895163,  9.15058848,
        4.65      ,  4.67319312,  3.95      ,  5.59161729,  0.4       ,
        2.57895163,  2.925     ,  6.4       ,  2.88571429,  1.2       ,
        6.56043128, 18.37714286,  2.57895163,  4.17483435,  0.12      ,
        4.67319312, 18.37714286,  6.56043128,  6.4       ,  7.62551466,
        6.56043128,  3.95      ,  2.57895163,  0.65      ,  2.57895163,
        2.57895163,  2.57895163,  6.4       ,  1.75      ,  2.57895163,
        3.95      ,  2.925     ,  6.56043128,  2.57895163,  9.15058848,
        6.20670617,  6.56043128,  4.67319312,  2.57895163,  4.17483435,
        2.62857143,  6.55235273,  4.17483435,  2.57895163,  2.57895163,
        2.7875    ,  6.56043128,  4.65      ,  1.09      ,  4.22445414,
        9.15058848,  4.1       ,  2.925     ,  0.65      ,  0.65      ,
        2.57895163,  2.57895163,  4.37921605,  0.78      ,  7.62551466,
        2.57895163,  6.        ,  2.57895163,  2.57895163,  9.65411729,
        2.57895163,  6.4       ,  6.09588271,  5.59161729,  2.57895163,
        6.4       ,  7.55470576,  0.9       ,  7.59588271,  4.65      ,
        6.        ,  6.20670617,  7.62551466, 11.25      ,  0.48      ,
        3.90411729,  1.2       ,  9.22139737,  0.72      ,  9.15058848,
        4.61082346,  2.57895163,  3.95      ,  3.95      ,  2.57895163,
        2.57895163])

# **Checking the accuracy**

In [19]:
regressor.score(X,y)

0.6146919239973325