In [1]:
import os, sys

In [2]:
from google.colab import drive

In [3]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
os.chdir('/content/drive/MyDrive')

sys.path.append("/content/drive/My Drive/")

In [5]:
import numpy as np

In [6]:
import matplotlib.pyplot as plt
import pandas as pd

# **Importing the dataset**

In [21]:
dataset = pd.read_csv('cardata.csv')

In [22]:
dataset

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [23]:
X = dataset.iloc[:, 3:4]   # Present_Price (independent variable)
y = dataset.iloc[:, 2]     # Selling_Price (dependent variable)

In [24]:
X

     Present_Price
0             5.59
1             9.54
2             9.85
3             4.15
4             6.87
..             ...
296          11.60
297           5.90
298          11.00
299          12.50
300           5.90

[301 rows x 1 columns]

In [25]:
y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

# **Encoding Categorical variable**

In [26]:
X = dataset.iloc[:, [0, 5]]

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [0, 1])
    ],
    remainder='passthrough'
)

X = ct.fit_transform(X)

In [28]:
X

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# **Splitting the dataset into the Training set and Test**

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/2)

# **Training the Multiple Linear Regression model on the Training set**

In [30]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [31]:
y_pred = regressor.predict(X_test)

In [32]:
y_pred

array([15.48672342,  7.10508513,  3.00781389,  0.475     ,  6.6411342 ,
        5.5       , 17.91285714,  8.24621933,  1.15      , 17.91285714,
        0.52      ,  8.24621933,  5.16497162,  3.00781389,  3.89491487,
       17.91285714,  3.00781389,  3.11666667,  6.6411342 ,  5.5       ,
        7.46836171,  3.89491487,  6.61198297,  0.775     ,  3.00781389,
        3.00781389,  4.61289901,  5.16497162,  4.925     ,  3.00781389,
        6.77005675,  3.00781389,  4.61289901, 17.91285714,  3.00781389,
        6.6411342 ,  3.11666667,  5.5       ,  3.00781389,  6.6411342 ,
        6.62245744,  1.2       ,  3.00781389,  0.35      ,  6.6411342 ,
        3.00781389,  2.25      ,  3.00781389,  3.00781389, 15.48672342,
        3.00781389,  6.61198297,  1.08666667,  0.55      , 15.48672342,
        6.10254256,  0.735     , 13.88163829,  5.86327658,  3.00781389,
        1.08666667,  6.48333333,  3.00781389,  4.925     ,  3.00781389,
        6.61198297,  8.24621933,  6.6411342 ,  3.49830496,  3.00781389,
        7.46836171,  4.61289901,  6.6411342 ,  6.62245744,  6.77005675,
        5.5       ,  5.16497162,  3.00781389,  4.925     ,  3.00781389,
        8.22754256,  0.3       ,  5.16497162,  0.36666667,  3.00781389,
        4.925     , 15.48672342,  3.98      ,  3.95      ,  4.49745744,
        3.98      ,  0.65      ,  2.25      ,  1.08666667,  6.61198297,
        3.00781389,  6.48333333,  6.48333333,  0.95      ,  4.925     ,
        3.00781389,  3.00781389,  2.06176471,  3.16666667,  5.10339009,
        4.925     ,  4.90254256,  3.00781389,  5.5       ,  3.00781389,
        3.00781389,  3.81390866,  3.49830496,  3.00781389,  1.08666667,
        3.00781389,  3.00781389,  3.11666667,  3.29745744,  6.48333333,
        3.49830496,  3.16666667,  6.6411342 ,  3.00781389,  7.10508513,
        3.00781389,  6.77005675,  3.00781389, 12.05254256,  6.61198297,
        5.10339009,  2.20882353,  3.00781389,  3.00781389,  6.61198297,
        3.00781389,  3.00781389,  3.00781389,  4.575     ,  4.49745744,
       15.48672342,  6.6411342 ,  2.25      ,  1.15      ,  0.45      ,
        6.10508513,  3.00781389,  6.6411342 ,  6.77005675,  3.95      ,
        3.49830496])

# **Checking the accuracy**

In [33]:
regressor.score(X,y)

0.7488411133652253